const TOPIC = {
    //DRUGS FROM 1-19
    ECSTASY: 1,
    OPIUM: 2,
    MORPHINE: 3,
    COCAINE: 4,
    HEROIN: 5,
    ALCOHOL: 6,
    CANNABIS: 7,
    AMPHETAMINES: 8,
    METAMPHETAMINES: 9,
    LSD: 10,
    //GENERIC TOPIS 20-39
    GEOPOLITICS: 20,
    RACISM: 21,
    POLITICS: 22,
    WORLD_WAR_1: 23,
    WORLD_WAR_2: 24,
    ECONOMICS: 25,
    SCIENCE: 26,
    HISTORY: 27,
    SHAM: 28,
    VIOLENCE: 29,
    CRIME: 30,
    CORRUPTION: 31,
    VIETNAM: 32,
    //HISTORICAL CHARACTERS 40-59
    HARRY_ANSLINGER: 40,
    RICHARD_NIXON: 41,
    //COUNTRIES 60-99
    COLOMBIA: 60,
    MEXICO: 61,
    US: 62,
    CANADA: 63,
    GERMANY: 64,
    CHINA: 65,
    UK: 66,
    FRANCE: 67,
    ITALY: 68,
    //AGENCIES
    DEA:91,
    CIA:92,
}

const LANGUAGE = {
    ES: 0,
    EN: 1
}
exports.LANGUAGE = LANGUAGE;
exports.TOPIC = TOPIC;
